services:
  api_usuarios:
      build: ./usuarios
      ports:
        - "8001:80"
      env_file:
        - ./usuarios/.env
      volumes:
        - ./usuarios:/code 
      depends_on:
        db_usuarios:
          condition: service_healthy

  db_usuarios:
    image: postgres:15
    container_name: postgres_db_usuarios
    env_file:
      - ./usuarios/.env
    ports:
      - "5434:5432"
    volumes:
      - postgres_usuarios_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  api_tienda:
      build: ./backend
      ports:
        - "8000:80"
      env_file:
        - ./backend/.env
      volumes:
        - ./backend:/code  
      command: fastapi dev main.py --port 80 --host 0.0.0.0
      depends_on:
        db_tienda:
          condition: service_healthy

  db_tienda:
    image: postgres:15
    container_name: postgres_db_tienda
    env_file:
      - ./backend/.env
    ports:
      - "5433:5432"
    volumes:
      - postgres_tienda_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    image: node:22
    working_dir: /app
    ports:
      - "5173:5173"
    env_file:
      - ./front/.env
    volumes:
      - ./front:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"

volumes:
  postgres_usuarios_data:
  postgres_tienda_data: