"""Inicial

Revision ID: 8161fe5a867c
Revises: 
Create Date: 2026-09-08 13:49:22.985825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8161fe5a867c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'tipo',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'cliente'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'tipo',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'cliente'::character varying"))
    # ### end Alembic commands ###
