"""elimina rol y tipo de user y activo de rol

Revision ID: eb2d11272f41
Revises: telefono_str
Create Date: 2026-09-17 12:25:03.452854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb2d11272f41'
down_revision: Union[str, Sequence[str], None] = 'telefono_str'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rol', 'activo')
    op.drop_column('user', 'rol')
    op.drop_column('user', 'tipo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('tipo', sa.VARCHAR(), server_default=sa.text("'cliente'::character varying"), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('rol', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('rol', sa.Column('activo', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
