FROM python:3.11-slim

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY . /code

EXPOSE 80

# Cambiamos "run" por "dev" para habilitar la recarga de archivos
CMD ["fastapi", "dev", "main.py", "--host", "0.0.0.0", "--port", "80"]